version: '3'

volumes:
  mongo-data-store:
  redis-data-store:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data-store:/data/db
    env_file:
      - .env

  redis:
    container_name: redis
    image: redis
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASS"
    env_file:
      - .env
    ports:
      - 6379:6379
    volumes:
      - redis-data-store:/data

  auth:
    container_name: auth-services
    build:
      context: ./
      dockerfile: ./apps/auth/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: npm run start:dev auth

  presence:
    container_name: presence-services
    build:
      context: ./
      dockerfile: ./apps/presence/Dockerfile
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - mongodb
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: npm run start:dev presence

  api:
    container_name: api-gateway
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    command: npm run start:dev api
    depends_on:
      - rabbitmq
      - mongodb
      - auth
      - presence
    env_file:
      - .env
    ports:
      - '1001:1000'
